name: flutter_date_picker_timeline
description: A Gregorian and Jalali customizable date picker as a horizontal timeline
version: 0.3.3
homepage: https://github.com/sobimor/flutter_date_picker_timeline

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  shamsi_date: ^1.0.1
  scroll_to_index: ^3.0.1

flutter:

  fonts:
    - family: Dana
      fonts:
        - asset: assets/fonts/dana.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito.ttf

 